name: testingenvfrom
secrets:
  - name: 'secretone'
  - name: 'secrettwo'
    prefix: 'TWO_'
configmaps:
  - name: 'configone'
    prefix: 'ONE_'
  - name: 'configtwo'
env_vars: 
  - key: APP_NAME
    value: BackOffice
  - key: BROADCAST_DRIVER
    value: log
  - key: CACHE_DRIVER
    value: file
  - key: SESSION_DRIVER
    value: file
  - key: SESSION_LIFETIME
    value: "120"
  - key: QUEUE_DRIVER
    value: sync
secretVolumes: 
  - name: pem-secret-volume
    secretName: apns-dev.pem
    defaultMode: 420
  - name: other-secret-volume
    secretName: other
    defaultMode: 420
volumeMounts: 
  - name: pem-secret-volume
    mountPath: /opt/app-root/src/storage/app/certificates
  - name: other-secret-volume=
    mountPath: /opt/app-root/src/storage/app/other