name: realworld
env_vars: 
  - key: APP_NAME
    value: BackOffice
imageStreamTag: "realworld:v0.0.9"
#
# This section will create two PVCs and mount them in the image. 
# Note that the default is ReadWriteOnce but you can override 
# by setting accessMode. 
# 
# Note if you let it default to ReadWriteOnce you need to change 
# the deployment strategy from the default Rolling to Recreate
#
strategy: Recreate
pvcs:
  - name: testpvc2
  - name: testpvc
volumeMounts: 
  - name: testpvc2
    mountPath: /opt/app-root/src/.data/
  - name: testpvc
    mountPath: /opt/app-root/testpvc