kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.name | quote }}
spec:
  {{- if .Values.host }}  
  host: {{ .Values.host | quote }}
  {{- end }}
  {{- if .Values.targetPort }}  
  port:
    targetPort: {{ .Values.targetPort | quote }}
  {{- end }}  
  {{- if .Values.termination }}  
  termination: {{ .Values.termination | quote }}
  {{- end }}
  {{- if .Values.tls }}
  tls:
    insecureEdgeTerminationPolicy: {{ .Values.insecureEdgeTerminationPolicy | default "Redirect" | quote }}
    caCertificate: |
{{ .Values.caCertificate | indent 6 }}
    certificate: |
{{ .Values.certificate | indent 6 }}
    key: |
{{ .Values.key | indent 6 }}
  {{- end }}
  to:
    kind: Service
    name: {{ .Values.name | quote }}
