kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.name | quote }}
spec:
  {{- if .Values.host }}  
  host: {{ .Values.host | quote }}
  {{- end }}
  {{- if .Values.targetPort }}  
  port:
    targetPort: {{ .Values.targetPort | quote }}
  {{- end }}  
  {{- if .Values.termination }}  
  termination: {{ .Values.termination | quote }}
  {{- end }}
  {{- if .Values.tls }}
  insecureEdgeTerminationPolicy: {{ .Values.insecureEdgeTerminationPolicy | default "Redirect" | quote }}
  caCertificate: |
    {{ .Values.caCertificate }}
  certificate: |
    {{ .Values.certificate }}
  key: |
    {{ .Values.key }}
  {{- end }}
  to:
    kind: Service
    name: {{ .Values.name | quote }}
